### ISSUE TITLE
[Suggest] Welcome ~> Awesome?

### ISSUE THREAD

**Issue by ghost** [meu32ki/eard-server#2]
README.mdで`Welcome to commit from you`にしたけど、WelcomeじゃなくてAwesomeのほうが良かったかもしれないけど英語苦手なフレンズなので一応伝えるだけー

**Comment by meu32ki** [comment]
welcome って受け入れるって意味があるのでそういうことで使った(？)よ
We welcome commit from you 
Awesomeは サイコー！って感じなので違うかなーと思い(´･ω･｀)

**Comment by ghost** [comment]
なるほどー？何となく(分かったような分からないような狭間に居るけど)雰囲気は分かった気がする
