### ISSUE TITLE
データベース接続部分について

### ISSUE THREAD

**Issue by kazuemon** [meu32ki/eard-server#9]
多分ローカル接続のみにしていると思うのですが、DBの接続情報をアップロードするのは問題ないとはいえないと思います

**Comment by meu32ki** [comment]
ご指摘どうもです。改善案としてはどのようにするのが良いのか、よろしければご教授願います。

**Comment by kazuemon** [comment]
**.gitignore(Git の管理に含めないファイルを指定するためのファイル)** を使用するのがいいと思われます。
私はGithubをあまり使わないためそれについてはよく分かっていないので、これらを参考にするといいと思います。
http://qiita.com/inabe49/items/16ee3d9d1ce68daa9fff
http://qiita.com/y_minowa/items/e3d8513dc31c1b378e0d

**Comment by kazuemon** [comment]
見たところ、すでに使用されていましたね()
よくわからないのですが別ファイルに記述(AuthData::getPassword()みたいな)して.gitignoreにそのファイルを指定するみたいなのが一番いいんでしょうかね...?
Gitはあまり扱わないのであってるかわかりませんが...

**Comment by ghost** [comment]
突然のコメント失礼します。
`.gitignore`に書くのが面倒というのであれば、ホームディレクトリなどリポジトリに関係のない場所に置くようにすればいいのでは無いでしょうか。     
こんな私めからの意見ではありますが、もし良ければご検討の程よろしくお願いします。

**Comment by meu32ki** [comment]
gitignoreにいれておきます、お二方ありがとうございます
